{
 "title": "Logs Overview",
 "tags": [ "Logging" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Logs/sec ONPREM/SNPAAS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasSub(sumSeries(perSecond(stats.gauges.logstash-onprem.api_snpass_eu.*)), 'logstash-onprem', 'ONPREM'), 2)"
    },
    {
     "target": "aliasByNode(aliasSub(sumSeries(perSecond(stats.gauges.elk-logstash.api_snpass_eu.*)), 'elk-logstash', 'SNPAAS'), 2)"
    }
   ]
  },
  {
   "title": "Total Logs SNPAAS/ONPREM",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(aliasSub(integral(perSecond(sumSeries(stats.gauges.elk-logstash.api_snpass_eu.*))), 'elk-logstash', 'SNPAAS'), 2)"
    },
    {
     "target": "aliasByNode(aliasSub(integral(perSecond(sumSeries(stats.gauges.logstash-onprem.api_snpass_eu.*))), 'logstash-onprem', 'ONPREM'), 2)"
    }
   ]
  },
  {
   "title": "SNPAAS Logs by CF Org",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(integral(perSecond(stats.gauges.elk-logstash.api_snpass_eu.*))), 4)"
    }
   ]
  },
  {
   "title": "ONPREM Logs by CF Org",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(integral(perSecond(sortByMaxima(stats.gauges.logstash-onprem.api_snpass_eu.*))), 4)"
    }
   ]
  },
  {
   "title": "SNPAAS Logs by Spaces",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(integral(perSecond(sortByMaxima(stats.gauges.elk-logstash.api_snpass_eu.*.*))), 4, 5)"
    }
   ]
  },
  {
   "title": "ONPREM Logs by Spaces",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(integral(perSecond(sortByMaxima(stats.gauges.logstash-onprem.api_snpass_eu.*.*))), 4, 5)"
    }
   ]
  },
  {
   "title": "Top 10 Busy Apps(ONPREM)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(currentAbove(integral(perSecond(sortByMaxima(stats.gauges.logstash-onprem.api_snpass_eu.*.*.*))), 1), 10), 4, 5, 6)"
    }
   ]
  },
  {
   "title": "Top 10 Busy Apps(SNPAAS)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(currentAbove(integral(perSecond(sortByMaxima(stats.gauges.elk-logstash.api_snpass_eu.*.*.*))), 1), 10), 4, 5, 6)"
    }
   ]
  }
 ]
}