{
 "title": "Go-graphite (Metrics, Agents, Statsd)",
 "tags": [ "METRICS" ],
 "time": { "from": "now-1h", "to": "now-2m" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_GRAPHITE", "query": "graphite" }
  ]
 },
 "panels": [
  {
   "title": "Relay metrics",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(summarize(nonNegativeDerivative(carbon.relays.graphite-statsd-relay_*.metricsReceived), '1minute', 'sum')), 'Relay received metrics p/m')"
    },
    {
     "target": "alias(sumSeries(summarize(nonNegativeDerivative(carbon.relays.graphite-statsd-relay_*.metricsSent), '1minute', 'sum')), 'Relay sent metrics p/m')"
    },
    {
     "target": "alias(derivative(sumSeries(carbon.relays.graphite-statsd-relay_*.metricsDropped)), 'Dropped metrics')"
    },
    {
     "target": "alias(sumSeries(carbon.relays.graphite-statsd-relay_*.metricsQueued), 'Metrics queued (all nodes) p/m')"
    },
    {
     "target": "alias(derivative(sumSeries(carbon.relays.graphite-statsd-relay_*.metricsBlackholed)), 'Metrics blackholed (all nodes) p/m')"
    }
   ]
  },
  {
   "title": "Relay metrics Queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(carbon.relays.graphite-statsd-relay_*.metricsQueued), 'Metrics queued all nodes')"
    },
    {
     "target": "aliasByNode(carbon.relays.graphite-statsd-relay_*.metricsQueued, 3, -2)"
    }
   ]
  },
  {
   "title": "Relay metrics Dropped",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(derivative(sumSeries(carbon.relays.graphite-statsd-relay_*.metricsDropped)), 'Dropped metrics')"
    },
    {
     "target": "aliasByNode(carbon.relays.graphite-statsd-relay_*.metricsDropped,3, -2)"
    }
   ]
  },
  {
   "title": "Go carbon agent metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(carbon.agents.graphite-backend.*.tcp.metricsReceived), 'Metrics received all nodes')"
    },
    {
     "target": "alias(sumSeries(carbon.agents.graphite-backend.*.cache.metrics), 'Metrics cached all nodes')"
    },
    {
     "target": "alias(sumSeries(carbon.agents.graphite-backend.*.cache.size), 'Cache size all nodes')"
    },
    {
     "target": "alias(sumSeries(carbon.agents.graphite-backend.*.persister.committedPoints), 'Committed points all nodes')"
    },
    {
     "target": "alias(sumSeries(carbon.agents.graphite-backend.*.persister.created), 'Created points all nodes')"
    }
   ]
  },
  {
   "title": "Stats metrics received p/m",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.statsd.graphite-*.metrics_received), 'Total')"
    },
    {
     "target": "stats.statsd.graphite-*.metrics_received"
    }
   ]
  },
  {
   "title": "Statsd Packets Received",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.statsd.graphite-*.packets_received), 'Packets received all nodes')"
    },
    {
     "target": "stats.statsd.graphite-*.packets_received"
    }
   ]
  },
  {
   "title": "Statsd Flush",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.statsd.graphite-*.graphiteStats.flush_length), 'Flush length all nodes')"
    },
    {
     "target": "stats.statsd.graphite-*.graphiteStats.flush_length"
    }
   ]
  },
  {
   "title": "Statsd time metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "stats.statsd.graphite-*.processing_time"
    },
    {
     "target": "stats.statsd.graphite-*.graphiteStats.flush_time"
    },
    {
     "target": "derivative(stats.statsd.graphite-*.graphiteStats.last_flush)"
    }
   ]
  }
 ]
}