{
 "title": "APP Overview",
 "tags": [ "snpaas" ],
 "time": { "from": "now-1h", "to": "now-1m" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "OrgName",
    "label": "OrgName",
    "query": "label_values(cf_application_info, organization_name)"
   },
   {
    "name": "SpaceName",
    "label": "SpaceName",
    "query": "label_values(cf_application_info{organization_name=~\"$OrgName\"},space_name)"
   },
   {
    "name": "AppName",
    "label": "AppName",
    "query": "label_values(cf_application_info{organization_name=~\"$OrgName\", space_name=~\"$SpaceName\"},application_name)"
   },
   {
    "name": "AppId",
    "label": "AppId",
    "query": "label_values(cf_application_info{organization_name=~\"$OrgName\", space_name=~\"$SpaceName\", application_name=~\"$AppName\"},application_id)"
   },
   {
    "name": "AppMemory",
    "query": "query_result(max(cf_application_memory_mb{application_id=~\"$AppId\"}))"
   },
   { "name": "Ratio_CPU_RAM", "query": "0.4444" }
  ]
 },
 "panels": [
  {
   "title": "Application Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cf_application_info{organization_name=~\"$OrgName\", space_name=~\"$SpaceName\", application_name=~\"$AppName\"}"
    }
   ]
  },
  {
   "title": "Memory Assigned by Instance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$AppMemory" }
   ]
  },
  {
   "title": "Total Memory Assigned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "$AppMemory * avg(cf_application_instances{application_id=~\"$AppId\", state=\"STARTED\"})"
    }
   ]
  },
  {
   "title": "Number of Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cf_application_instances{state=\"STARTED\",application_name=\"$AppName\", space_name=\"$SpaceName\", organization_name=\"$OrgName\"})"
    }
   ]
  },
  {
   "title": "Total Memory Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg(firehose_container_metric_memory_bytes{application_id=~\"$AppId\"}) by (instance_index)) /1024/1024"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(min(firehose_container_metric_memory_bytes{application_id=~\"$AppId\"}) by (application_id) / min(firehose_container_metric_memory_bytes_quota{application_id=~\"$AppId\"}) by (application_id) * 100)"
    }
   ]
  },
  {
   "title": "Request Rate by Status Code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(firehose_http_start_stop_requests{application_id=~\"$AppId\"}[$interval])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Request Rate by HTTP Method",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(firehose_http_start_stop_requests{application_id=~\"$AppId\"}[$interval])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Request Rate by Instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(firehose_http_start_stop_requests{application_id=~\"$AppId\"}[$interval])) by (instance_id)",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "CPU Quota Usage by Instance",
   "type": "graph",
   "description": "100% = the CPU quota allocated to each instance. It is possible to go over 100% if there is spare capacity on the cell.\n\nThe amount of CPU guaranteed to an instance is proportional to its memory, so doubling memory will also double guaranteed CPU. However if you need more CPU, it is usually better to keep memory low and instead increase the number of instances.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max(firehose_container_metric_cpu_percentage{application_id=~\"$AppId\"}) by (instance_index) / ($AppMemory/1024 * $Ratio_CPU_RAM)",
     "legendFormat": "{{instance_index}}"
    },
    { "expr": "100", "legendFormat": "quota" }
   ]
  },
  {
   "title": "Memory Usage by Instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_container_metric_memory_bytes{application_id=~\"$AppId\"}) by (instance_index) / (1024*1024)",
     "legendFormat": "{{ instance_index }}"
    },
    { "expr": "$AppMemory", "legendFormat": "Memory Limit" }
   ]
  },
  {
   "title": "Disk Usage by Instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_container_metric_disk_bytes{application_id=~\"$AppId\"}) by(instance_index) ",
     "legendFormat": "{{instance_index}}"
    },
    {
     "expr": "max(firehose_container_metric_disk_bytes_quota{application_id=~\"$AppId\"})",
     "legendFormat": "Quota"
    }
   ]
  }
 ]
}