{
 "title": "CF Cells Performance",
 "tags": [ "snpaas" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "TCP Errors",
   "type": "graph",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs[5m]) * on(instance) group_right label_replace(bosh_job_healthy{bosh_deployment=\"cf\", bosh_job_name=\"diego-cell\"},\"instance\", \"$1:9100\", \"bosh_job_ip\", \"(.*)\")"
    }
   ]
  },
  {
   "title": "Load1",
   "type": "graph",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Per VM" }
   ],
   "targets": [
    {
     "expr": "node_load1 * on(instance) group_right label_replace(bosh_job_healthy{bosh_deployment=\"cf\", bosh_job_name=\"diego-cell\"},\"instance\", \"$1:9100\", \"bosh_job_ip\", \"(.*)\")"
    }
   ]
  },
  {
   "title": "Rate node_cpu_seconds_total  (cpu not idle)",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[5m])) * 100)) * on(instance) group_right label_replace(bosh_job_healthy{bosh_deployment=\"cf\", bosh_job_name=\"diego-cell\"},\"instance\", \"$1:9100\", \"bosh_job_ip\", \"(.*)\"))"
    }
   ]
  },
  {
   "title": "Rate node_disk_io_time_seconds_total",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(node_disk_io_time_seconds_total[5m])) by (instance)) * on(instance) group_right label_replace(bosh_job_healthy{bosh_deployment=\"cf\", bosh_job_name=\"diego-cell\"},\"instance\", \"$1:9100\", \"bosh_job_ip\", \"(.*)\")"
    }
   ]
  },
  {
   "title": "Rate node_disk_write_time_seconds_total",
   "type": "graph",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(node_disk_write_time_seconds_total[5m])) by (instance)) * on(instance) group_right label_replace(bosh_job_healthy{bosh_deployment=\"cf\", bosh_job_name=\"diego-cell\"},\"instance\", \"$1:9100\", \"bosh_job_ip\", \"(.*)\")"
    }
   ]
  }
 ]
}