{
 "title": "CF Cells Capacity",
 "tags": [ "snpaas" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(firehose_value_metric_rep_capacity_total_containers, environment)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(firehose_value_metric_rep_capacity_total_containers{environment=~\"$environment\"}, bosh_deployment)"
   },
   {
    "name": "bosh_job_name",
    "label": "Job",
    "query": "label_values(firehose_value_metric_rep_capacity_total_containers{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}, bosh_job_name)"
   },
   { "name": "instance_sizes", "label": "Instance Sizes", "query": "256,512,1024,2048,4096" }
  ]
 },
 "panels": [
  {
   "title": "Number of Cells",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(firehose_value_metric_rep_garden_health_check_failed{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}) by (bosh_job_ip))\n"
    }
   ]
  },
  {
   "title": "Capacity Plan (per instance size)",
   "type": "bargauge",
   "description": "The amount of application instances of different sizes which can be deployed right now in SNPaaS",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(avg(firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}) by (bosh_job_ip)/(4096)))",
     "legendFormat": "4096 MB instances"
    },
    {
     "expr": "sum(floor(avg(firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}) by (bosh_job_ip)/(2048)))",
     "legendFormat": "2048 MB instances"
    },
    {
     "expr": "sum(floor(avg(firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}) by (bosh_job_ip)/(1024)))",
     "legendFormat": "1024 MB instances"
    },
    {
     "expr": "sum(floor(avg(firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}) by (bosh_job_ip)/(512)))",
     "legendFormat": "512 MB instances"
    },
    {
     "expr": "sum(floor(avg(firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}) by (bosh_job_ip)/(256)))",
     "legendFormat": "256 MB instances"
    }
   ]
  },
  {
   "title": "Total Cell Memory",
   "type": "graph",
   "description": "Cumulative used and available MiB of memory to allocate to containers.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_total_memory{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip)) - sum(avg(firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Total Cell Disk",
   "type": "graph",
   "description": "Cumulative used and available MiB of disk to allocate to containers.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_total_disk{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip)) - sum(avg(firehose_value_metric_rep_capacity_remaining_disk{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(avg(firehose_value_metric_rep_capacity_remaining_disk{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "System Memory Used Per Cell",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes *100) * on(instance) group_right label_replace(bosh_job_healthy{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}, \"instance\", \"$1:9100\", \"bosh_job_ip\", \"(.*)\")",
     "legendFormat": "{{bosh_job_name}}/{{ bosh_job_index}}/{{ bosh_job_az }}"
    }
   ]
  },
  {
   "title": "Allocated Memory Per Cell",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg((firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}) / firehose_value_metric_rep_capacity_total_memory{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"} * 100) by (bosh_job_ip)) * on(bosh_job_ip) group_right bosh_job_healthy",
     "legendFormat": "{{bosh_job_name}}/{{ bosh_job_index}}/{{ bosh_job_az }}"
    }
   ]
  },
  {
   "title": "Containers per Cell",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(firehose_value_metric_rep_capacity_total_containers{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"} - firehose_value_metric_rep_capacity_remaining_containers{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}) by(bosh_job_ip) * on(bosh_job_ip) group_right bosh_job_healthy",
     "legendFormat": "{{bosh_job_name}}/{{ bosh_job_index}}/{{ bosh_job_az }}"
    }
   ]
  },
  {
   "title": "Allocated Disk Per Cell",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg((firehose_value_metric_rep_capacity_remaining_disk{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}) / firehose_value_metric_rep_capacity_total_disk{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"} * 100) by (bosh_job_ip)) * on(bosh_job_ip) group_right bosh_job_healthy",
     "legendFormat": "{{bosh_job_name}}/{{ bosh_job_index}}/{{ bosh_job_az }}"
    }
   ]
  }
 ]
}