{
 "title": "CF: Doppler Server v3",
 "tags": [
  "cf",
  "loggregator"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(firehose_counter_event_loggregator_doppler_ingress_total, environment)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(firehose_counter_event_loggregator_doppler_ingress_total{environment=~\"$environment\"}, bosh_deployment)"
   },
   { "name": "interval", "query": "5m,1h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Sinks",
   "type": "graph",
   "description": "Instantaneous number of sinks known to the SinkManager.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(avg(firehose_value_metric_loggregator_doppler_container_metric_sinks{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Container Metric"
    },
    {
     "expr": "sum(avg(firehose_value_metric_loggregator_doppler_dump_sinks{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "Dump"
    }
   ]
  },
  {
   "title": "Messages Received by Listeners",
   "type": "graph",
   "description": "number of messages received by each Doppler instance (UDP, TCP, TLS).",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(firehose_counter_event_loggregator_doppler_ingress_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[$interval])) \nby(bosh_job_ip)",
     "legendFormat": "{{ bosh_job_ip }}"
    }
   ]
  },
  {
   "title": "Doppler Subscriptions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(firehose_value_metric_loggregator_doppler_subscriptions{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "{{ bosh_job_ip }}"
    }
   ]
  },
  {
   "title": "Doppler Dropped Messages Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(firehose_counter_event_loggregator_doppler_dropped_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[$interval])) by(bosh_job_ip)",
     "legendFormat": "{{ bosh_job_name }}"
    }
   ]
  },
  {
   "title": "Doppler Dropped Messages Percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(firehose_counter_event_loggregator_doppler_dropped_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[$interval]))\n/\nsum(rate(firehose_counter_event_loggregator_doppler_ingress_total{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\"}[$interval]))",
     "legendFormat": "dropped %"
    }
   ]
  }
 ]
}