{
 "title": "CF Requests",
 "tags": [ "snpaas" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Internal Request/s  (total)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(gorouter_http_requests_total[5m]) * on(instance) group_right label_replace(bosh_job_healthy{bosh_deployment=\"cf\", bosh_job_name=\"internal_router\"},\"instance\", \"$1:3903\", \"bosh_job_ip\", \"(.*)\")",
     "legendFormat": "Internal Gorouter {{bosh_job_index}} ({{bosh_job_az}}) {{bosh_job_ip}}"
    },
    {
     "expr": "sum(irate(gorouter_http_requests_total[5m]) * on(instance) group_right label_replace(bosh_job_healthy{bosh_deployment=\"cf\", bosh_job_name=\"internal_router\"},\"instance\", \"$1:3903\", \"bosh_job_ip\", \"(.*)\"))",
     "legendFormat": "Internal Total"
    }
   ]
  },
  {
   "title": "Internal requests by route (total)",
   "type": "grafana-piechart-panel",
   "description": "Distribution of total amount of Internal requests processed in the time frame",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(gorouter_http_requests_app) by (route,instance) * on(instance) group_left label_replace(bosh_job_healthy{bosh_deployment=\"cf\", bosh_job_name=\"internal_router\"},\"instance\", \"$1:3903\", \"bosh_job_ip\", \"(.*)\")) by (route) > 0",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Public Request/s  (total)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(gorouter_http_requests_total[5m]) * on(instance) group_right label_replace(bosh_job_healthy{bosh_deployment=\"cf\", bosh_job_name=\"router\"},\"instance\", \"$1:3903\", \"bosh_job_ip\", \"(.*)\")",
     "legendFormat": "Gorouter {{bosh_job_index}} ({{bosh_job_az}}) {{bosh_job_ip}}"
    },
    {
     "expr": "sum(irate(gorouter_http_requests_total[5m]) * on(instance) group_right label_replace(bosh_job_healthy{bosh_deployment=\"cf\", bosh_job_name=\"router\"},\"instance\", \"$1:3903\", \"bosh_job_ip\", \"(.*)\"))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Public requests by route (total)",
   "type": "grafana-piechart-panel",
   "description": "Distribution of total amount of public requests processed in the time frame",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 45 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(gorouter_http_requests_app) by (route,instance) * on(instance) group_left label_replace(bosh_job_healthy{bosh_deployment=\"cf\", bosh_job_name=\"router\"},\"instance\", \"$1:3903\", \"bosh_job_ip\", \"(.*)\")) by (route) > 0",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}