{
 "title": "SPACE Overview",
 "tags": [ "snpaas" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "OrgName",
    "label": "OrgName",
    "query": "label_values(cf_application_info, organization_name)"
   },
   {
    "name": "OrgId",
    "label": "OrgId",
    "query": "label_values(cf_application_info{organization_name=~\"$OrgName\",},organization_id)"
   },
   {
    "name": "SpaceName",
    "label": "SpaceName",
    "query": "label_values(cf_application_info{organization_name=~\"$OrgName\"},space_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory quota for $OrgName",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "cf_organization_total_memory_mb_quota{organization_name=\"$OrgName\"}*(1000/1024)"
    }
   ]
  },
  {
   "title": "Total Memory Allocated",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cf_application_memory_mb{organization_name=\"$OrgName\", space_name=\"$SpaceName\"} * on (application_id) group_right(space_name) sum(cf_application_instances{state=\"STARTED\"}) by (application_id)) "
    }
   ]
  },
  {
   "title": "Total Number of Apps",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(cf_application_info{organization_name=\"$OrgName\", space_name=\"$SpaceName\" ,state=\"STARTED\"}) by (application_name))",
     "legendFormat": "$OrgName-$SpaceName"
    }
   ]
  },
  {
   "title": "Total Number of Instances",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(cf_application_instances{organization_name=\"$OrgName\", space_name=\"$SpaceName\",state=\"STARTED\"}) by (space_name))",
     "legendFormat": "$OrgName-$SpaceName"
    }
   ]
  },
  {
   "title": "Average assigned memory utilization in space $SpaceName",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "avg((sum(min(firehose_container_metric_memory_bytes/1024/1024) by (instance_index, application_id)) by (application_id) / on(application_id) group_right(space_name) (cf_application_memory_mb{organization_name=\"$OrgName\", space_name=\"$SpaceName\"} * on (application_id) group_left(space_name) sum(cf_application_instances) by (application_id)))*100) by (organization_name)"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "Scale the quota when turned red",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "100/min(cf_organization_total_memory_mb_quota{organization_name=\"$OrgName\"}*(1000/1024))*sum(cf_application_memory_mb{organization_name=\"$OrgName\"} * on (application_id) group_right(space_name) sum(cf_application_instances{state=\"STARTED\"}) by (application_id))"
    }
   ]
  },
  {
   "title": "Stopped applications",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sort(cf_application_info{organization_name=\"$OrgName\", space_name=\"$SpaceName\", state=\"STOPPED\"})",
     "legendFormat": "{{application_name}}"
    },
    {}
   ]
  },
  {
   "title": "Memory Utilization per App",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sort_desc(max((avg(min(firehose_container_metric_memory_bytes/1024/1024) by (instance_index, application_id)) by (application_id) / on(application_id) group_right(space_name) (cf_application_memory_mb * on (application_id) group_left(space_name) sum(cf_application_instances{organization_name=\"$OrgName\", space_name=\"$SpaceName\", state=\"STARTED\"}) by (application_id)))*100) by (application_name))",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  {
   "title": "apps with crashed instances",
   "type": "yesoreyeram-boomtable-panel",
   "description": "No Data is good ;) here. Shows application whose desired number of instance are greater than number of running instances",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "min(cf_application_instances{organization_name=~\"$OrgName\",space_name=\"$SpaceName\", state=\"STARTED\"} - cf_application_instances_running{organization_name=~\"engineering-enablement\"}>0) by (application_name)",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  {
   "title": "Total Number of Instances",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(cf_application_instances{organization_name=\"$OrgName\", space_name=\"$SpaceName\",state=\"STARTED\"}) by (space_name))",
     "legendFormat": "$OrgName-$SpaceName"
    }
   ]
  }
 ]
}