{
 "title": "CF: Platform Overview",
 "tags": [ "snpaas" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Diego Cells Status",
   "type": "singlestat",
   "description": "Status of all Diego cells",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(firehose_value_metric_rep_unhealthy_cell)"
    }
   ]
  },
  {
   "title": "MySQL Status",
   "type": "singlestat",
   "description": "MySQL Status",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "Diego Cells Remaining Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_rep_capacity_remaining_memory) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "{{bosh_job_ip}}"
    }
   ]
  },
  {
   "title": "Diego Cells Remaining Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_value_metric_rep_capacity_remaining_disk) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "{{bosh_job_ip}}"
    }
   ]
  },
  {
   "title": "Go-Router Rate Requests per second",
   "type": "graph",
   "description": "Successful and failed requests received per second during the last 5 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(firehose_counter_event_gorouter_total_requests_total[5m])) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "{{bosh_job_ip}}"
    }
   ]
  },
  {
   "title": "Go-Router Rate Responses per second",
   "type": "graph",
   "description": "HTTP responses per second during the last 5 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(rate(firehose_counter_event_gorouter_responses_2_xx_total[5m])) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(avg(rate(firehose_counter_event_gorouter_responses_3_xx_total[5m])) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(avg(rate(firehose_counter_event_gorouter_responses_4_xx_total[5m])) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(avg(rate(firehose_counter_event_gorouter_responses_5_xx_total[5m])) by(bosh_deployment, bosh_job_name, bosh_job_ip))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Go-Router Total Exhausted Connections",
   "type": "graph",
   "description": "Go-Router Total Exhausted Connections",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(firehose_counter_event_gorouter_backend_exhausted_conns_total[5m])) by(bosh_deployment, bosh_job_name, bosh_job_ip)",
     "legendFormat": "{{bosh_job_ip}}",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "VM's CPU usage above 80%",
   "type": "graph",
   "description": "VM's CPU usage above 80%",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bosh_job_cpu_user > 80",
     "legendFormat": "{{bosh_job_name}} {{bosh_job_ip}}"
    }
   ]
  },
  {
   "title": "VM's Memory usage above 80%",
   "type": "graph",
   "description": "VM's Memory usage above 80%",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bosh_job_mem_percent > 80",
     "legendFormat": "{{bosh_job_name}} {{bosh_job_ip}}"
    }
   ]
  },
  {
   "title": "VM's Persistent Disk usage above 80%",
   "type": "graph",
   "description": "VM's Persistent Disk usage above 80%",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(bosh_job_persistent_disk_percent) by(bosh_deployment, bosh_job_name, bosh_job_ip) > 80",
     "legendFormat": "{{bosh_job_name}} ({{bosh_job_ip}})"
    }
   ]
  },
  {
   "title": "MySQL Questions",
   "type": "graph",
   "description": "MySQL Questions per second",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_questions[5m]) or irate(mysql_global_status_questions[5m])",
     "legendFormat": "Questions"
    }
   ]
  }
 ]
}