{
 "title": "Varnish",
 "tags": [
  "snpaas",
  "varnish"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "varnish_instance",
    "label": "Instance",
    "query": "label_values(varnish_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "cluster" },
  {
   "title": "Cache Hit Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(( rate(varnish_main_cache_hit{instance=~\"^($varnish_instance).*\"}[5m]) / rate(varnish_main_client_req{instance=~\"^($varnish_instance).*\"}[5m]) ))"
    }
   ]
  },
  {
   "title": "Frontend Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(varnish_main_client_req{instance=~\"^($varnish_instance).*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Backend Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(varnish_main_backend_req{instance=~\"^($varnish_instance).*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(varnish_main_sessions_total{instance=~\"^($varnish_instance).*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Cache Hit",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(varnish_main_cache_hit{instance=~\"^($varnish_instance).*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Loaded VMODs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(varnish_main_vmods{instance=~\"^($varnish_instance).*\"})"
    }
   ]
  },
  {
   "title": "Backend Up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "scalar(count(varnish_main_backend_unhealthy{instance=~\"^($varnish_instance).*\"} == 0))"
    }
   ]
  },
  {
   "title": "Backend Down",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(varnish_main_backend_unhealthy{instance=~\"^($varnish_instance).*\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(varnish_main_uptime{instance=~\"^($varnish_instance).*\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "varnish_version{instance=~\"^($varnish_instance).*\"}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_client_req{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "frontend"
    },
    {
     "expr": "sum(irate(varnish_main_backend_req{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "backend"
    },
    {
     "expr": "sum(varnish_main_fetch_total{instance=~\"^($varnish_instance).*\"})",
     "legendFormat": "fetch total"
    }
   ]
  },
  {
   "title": "Cache hits",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(varnish_main_cache_hit{instance=~\"^($varnish_instance).*\"}[5m]) / rate(varnish_main_client_req{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "cache hit %"
    },
    {
     "expr": "avg(1 - (rate(varnish_main_cache_hit{instance=~\"^($varnish_instance).*\"}[5m]) / rate(varnish_main_client_req{instance=~\"^($varnish_instance).*\"}[5m])))",
     "legendFormat": "cache miss %"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_s_resp_hdrbytes{instance=~\"^($varnish_instance).*\"}[5m]) + irate(varnish_main_s_resp_bodybytes{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "frontend"
    },
    {
     "expr": "sum(irate(varnish_backend_beresp_hdrbytes{instance=~\"^($varnish_instance).*\"}[5m]) + irate(varnish_backend_beresp_bodybytes{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "backend"
    },
    {
     "expr": "sum(irate(varnish_backend_beresp_hdrbytes{instance=~\"^($varnish_instance).*\"}[5m]) + irate(varnish_backend_beresp_bodybytes{instance=~\"^($varnish_instance).*\"}[5m])) by (backend)",
     "legendFormat": "backend {{ backend }}"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_n_expired{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(irate(varnish_main_n_lru_moved{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "LRU moved"
    },
    {
     "expr": "sum(irate(varnish_main_n_lru_nuked{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "LRU nuked"
    },
    {
     "expr": "sum(varnish_sma_g_bytes{type=\"s0\", instance=~\"^($varnish_instance).*\"})",
     "legendFormat": "mem used"
    }
   ]
  },
  {
   "title": "Thread pool",
   "type": "graph",
   "description": "Counts how many times varnishd hits the maximum allowed number of threads. The maximum number of Varnish threads is given by the parameter thread_pool_max. Issue the command varnishadm param.show thread_pool_max to see this parameter.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(varnish_main_threads_limited[5m]))\n",
     "legendFormat": "varnish_main_threads_limited"
    },
    {}
   ]
  },
  {
   "title": "varnish_main_ws_backend_overflow",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(varnish_main_ws_backend_overflow{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "varnish_main_ws_backend_overflow"
    },
    { "legendFormat": "varnish_mempool_timeout" }
   ]
  },
  {
   "title": "varnish_main_fetch \"type\"",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(type) (rate(varnish_main_fetch{}[5m]))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "varnish_mempool_timeout",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(varnish_mempool_timeout{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "varnish_mempool_timeout"
    },
    { "legendFormat": "varnish_mempool_timeout" }
   ]
  }
 ]
}