{
 "title": "App Logging Stats",
 "tags": [ "Logging" ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "App Logs by CF Org",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(stats.gauges.syslog-app-drain.api_snpaas_eu.*), 4)"
    }
   ]
  },
  {
   "title": "App Log Total",
   "type": "singlestat",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(stats.gauges.syslog-app-drain.api_snpaas_eu.*)"
    }
   ]
  },
  {
   "title": "App Log STDERR & STDOUT",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sortByMaxima(stats.gauges.syslog-app-drain.*.*.*.*.*)"
    }
   ]
  },
  {
   "title": "App Log by Spaces",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sortByMaxima(stats.gauges.syslog-app-drain.api_snpaas_eu.*.*)"
    }
   ]
  },
  {
   "title": "App Logs by CF APPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(stats.gauges.syslog-app-drain.*.*.*.*), 4, 5, 6)"
    }
   ]
  }
 ]
}