{
 "title": "CF: Apps Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(cf_application_info, environment)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(cf_application_info{environment=~\"$environment\"}, deployment)"
   },
   {
    "name": "cf_organization_name",
    "label": "Organization",
    "query": "label_values(cf_application_info{environment=~\"$environment\",deployment=~\"$bosh_deployment\"}, organization_name)"
   },
   {
    "name": "space_name",
    "label": "Space",
    "query": "label_values(cf_application_info{environment=~\"$environment\",deployment=~\"$bosh_deployment\",organization_name=~\"$cf_organization_name\"}, space_name)"
   },
   {
    "name": "cf_application_name",
    "label": "Application",
    "query": "label_values(cf_application_info{environment=~\"$environment\",deployment=~\"$bosh_deployment\",organization_name=~\"$cf_organization_name\", space_name=~\"$space_name\"}, application_name)"
   },
   {
    "name": "cf_application_id",
    "label": "Application ID",
    "query": "label_values(cf_application_info{environment=~\"$environment\",deployment=~\"$bosh_deployment\",organization_name=~\"$cf_organization_name\", space_name=~\"$space_name\",application_name=~\"$cf_application_name\"}, application_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Application State",
   "type": "singlestat",
   "description": "Application State",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "count(cf_application_info{environment=~\"$environment\",deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}) by(state)",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "graph",
   "description": "Number of Application Instances",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "min(cf_application_instances{environment=~\"$environment\",deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "Desired"
    },
    {
     "expr": "min(cf_application_instances_running{environment=~\"$environment\",deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Rate Requests per second",
   "type": "graph",
   "description": "Requests per second during the last 5 minutes.",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(firehose_http_start_stop_requests{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}[5m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average Application % CPU Usage.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_container_metric_cpu_percentage{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "graph",
   "description": "Response Size.",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_http_start_stop_response_size_bytes_sum{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"} / firehose_http_start_stop_response_size_bytes_count{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Rate Requests by Status Code per second",
   "type": "graph",
   "description": "Requests by status code per second during the last 5 minutes.",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(firehose_http_start_stop_requests{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}[5m])) by(status_code)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Rate Requests by Application Instance per second",
   "type": "graph",
   "description": "Requests per application instance per second during the last 5 minutes.",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(firehose_http_start_stop_requests{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}[5m])) by(instance_id)",
     "legendFormat": "{{ instance_id }}"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Average Application Memory Usage.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_container_metric_memory_bytes{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(firehose_container_metric_memory_bytes_quota{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "Memory Usage by Application Instance",
   "type": "graph",
   "description": "Memory Usage by Application Instance",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_container_metric_memory_bytes{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}) by(instance_index) ",
     "legendFormat": "{{ instance_index }}"
    },
    {
     "expr": "avg(firehose_container_metric_memory_bytes_quota{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "Allocated Disk Space  by Application Instance",
   "type": "graph",
   "description": "Allocated Disk Space  by Application Instance.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_container_metric_disk_bytes{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}) by(instance_index) ",
     "legendFormat": "{{ instance_index }}"
    },
    {
     "expr": "avg(firehose_container_metric_disk_bytes_quota{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "Organization Memory Consumption",
   "type": "graph",
   "description": "Total Memory Used and Quota for this Organization.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg(cf_application_memory_mb{environment=~\"$environment\",deployment=~\"$bosh_deployment\",organization_name=~\"$cf_organization_name\"}) by(application_id))",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(cf_organization_total_memory_mb_quota{environment=~\"$environment\",deployment=~\"$bosh_deployment\",organization_name=~\"$cf_organization_name\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "Organization Disk Consumption",
   "type": "graph",
   "description": "Total Disk allocated and Quota for this Organization.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg(cf_application_disk_quota_mb{environment=~\"$environment\",deployment=~\"$bosh_deployment\",organization_name=~\"$cf_organization_name\"}) by(application_id))",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(cf_organization_total_memory_mb_quota{environment=~\"$environment\",deployment=~\"$bosh_deployment\",organization_name=~\"$cf_organization_name\"})",
     "legendFormat": "Quota"
    }
   ]
  }
 ]
}