{
 "title": "Logstash JVM metrics overview",
 "description": "Logstash monitoring",
 "tags": [
  "logging",
  "logstash",
  "jvm"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "pipeline",
    "label": "Pipeline",
    "query": "label_values(logstash_node_pipeline_duration_seconds_total, pipeline)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(logstash_node_pipeline_duration_seconds_total{pipeline=~\"$pipeline\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Heap used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Heap" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "logstash_node_mem_heap_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - heap used"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "logstash_node_process_open_filedescriptors{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "GCs" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "rate(logstash_node_gc_collection_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} - {{collector}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "GCs" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "rate(logstash_node_gc_collection_duration_seconds_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} - {{collector}}"
    }
   ]
  }
 ]
}